export const CardsDB = {
  1: [
    {
      id: "carta1-nv1",
      name: "O Cavaleiro",
      img: "systems/tm/styles/assets/cards/1_1.webp",
      buff1: "letality",
      buff2: "virtue",
      hp: 2,
      description: "",
    },
    {
      id: "carta2-nv1",
      name: "O Plebeu",
      img: "systems/tm/styles/assets/cards/1_2.webp",
      buff1: "erudition",
      buff2: "impulse",
      hp: 1,
      description: "Resistência e estabilidade interior.",
    },
    {
      id: "carta3-nv1",
      name: "O Clérigo",
      img: "systems/tm/styles/assets/cards/1_3.webp",
      buff1: "virtue",
      buff2: "dexterity",
      hp: 3,
      description: "A centelha mágica pulsa em seu sangue.",
    },
    {
      id: "carta4-nv1",
      name: "O Mago",
      img: "systems/tm/styles/assets/cards/1_4.webp",
      buff1: "arcana",
      buff2: "erudition",
      hp: 1,
      description: "Sabedoria e espiritualidade cultivadas.",
    },
    {
      id: "carta5-nv1",
      name: "O Soldado",
      img: "systems/tm/styles/assets/cards/1_5.webp",
      buff1: "impulse",
      buff2: "letality",
      hp: 3,
      description: "Reflexos e brutalidade predatória.",
    },
    {
      id: "carta6-nv1",
      name: "A Cigana",
      img: "systems/tm/styles/assets/cards/1_6.webp",
      buff1: "dexterity",
      buff2: "arcana",
      hp: 1,
      description: "Um corpo moldado pela sobrevivência.",
    }
  ],

   2: [
    {
      id: "carta1-nv2",
      name: "O Astrólogo",
      img: "systems/tm/styles/assets/cards/2_1.webp",
      buff1: "erudition",
      buff2: "arcana",
      hp: 1,
      description: "Um corpo moldado pela sobrevivência.",
    },
    {
      id: "carta2-nv2",
      name: "O Bruxo",
      img: "systems/tm/styles/assets/cards/2_2.webp",
      buff1: "arcana",
      buff2: "dexterity",
      hp: 2,
      description: "Um corpo moldado pela sobrevivência.",
    },
    {
      id: "carta3-nv2",
      name: "O Caçador",
      img: "systems/tm/styles/assets/cards/2_3.webp",
      buff1: "letality",
      buff2: "erudition",
      hp: 1,
      description: "Um corpo moldado pela sobrevivência.",
    },
    {
      id: "carta4-nv2",
      name: "O Mercenário",
      img: "systems/tm/styles/assets/cards/2_4.webp",
      buff1: "dexterity",
      buff2: "letality",
      hp: 3,
      description: "Um corpo moldado pela sobrevivência.",
    },
    {
      id: "carta5-nv2",
      name: "O Nobre",
      img: "systems/tm/styles/assets/cards/2_5.webp",
      buff1: "virtue",
      buff2: "impulse",
      hp: 2,
      description: "Um corpo moldado pela sobrevivência.",
    },
    {
      id: "carta6-nv2",
      name: "O Ferreiro",
      img: "systems/tm/styles/assets/cards/2_6.webp",
      buff1: "impulse",
      buff2: "virtue",
      hp: 2,
      description: "Um corpo moldado pela sobrevivência.",
    }
  ],
  3: [ /* ... */ ],
};
