export const CardsDB = {
  1: [
    {
      id: "carta1-nv1",
      name: "Espada Rápida",
      img: "icons/svg/sword.svg",
      buff1: "dexterity",
      buff2: "letality",
      hp: 0,
      description: "Agilidade e precisão aumentadas.",
    },
    {
      id: "carta2-nv1",
      name: "Corpo Resoluto",
      img: "icons/svg/shield.svg",
      buff1: "impulse",
      buff2: "virtue",
      hp: 2,
      description: "Resistência e estabilidade interior.",
    },
    {
      id: "carta3-nv1",
      name: "Chama Interior",
      img: "icons/svg/fire.svg",
      buff1: "arcana",
      buff2: "erudition",
      hp: 1,
      description: "A centelha mágica pulsa em seu sangue.",
    },
    {
      id: "carta4-nv1",
      name: "Tradição Ancestral",
      img: "icons/svg/book.svg",
      buff1: "erudition",
      buff2: "virtue",
      hp: 0,
      description: "Sabedoria e espiritualidade cultivadas.",
    },
    {
      id: "carta5-nv1",
      name: "Instinto de Fera",
      img: "icons/svg/pawprint.svg",
      buff1: "letality",
      buff2: "dexterity",
      hp: 0,
      description: "Reflexos e brutalidade predatória.",
    },
    {
      id: "carta6-nv1",
      name: "Vitalidade Bruta",
      img: "icons/svg/heal.svg",
      buff1: "impulse",
      buff2: "letality",
      hp: 4,
      description: "Um corpo moldado pela sobrevivência.",
    }
  ],

   2: [
    {
      id: "carta1-nv2",
      name: "Disciplina Rígida",
      img: "icons/svg/anchor.svg",
      buff1: "virtue",
      buff2: "dexterity",
      hp: 1,
      description: "Controle mental forjado na dor.",
    },
    {
      id: "carta2-nv2",
      name: "Fôlego de Ferro",
      img: "icons/svg/breath.svg",
      buff1: "impulse",
      buff2: "arcana",
      hp: 3,
      description: "Resistência bruta alimenta o poder interno.",
    },
    {
      id: "carta3-nv2",
      name: "Estudo Obsessivo",
      img: "icons/svg/lamp.svg",
      buff1: "erudition",
      buff2: "virtue",
      hp: 0,
      description: "Nada supera a mente disciplinada.",
    },
    {
      id: "carta4-nv2",
      name: "Explosão Selvagem",
      img: "icons/svg/explosion.svg",
      buff1: "letality",
      buff2: "impulse",
      hp: 0,
      description: "Fúria que transforma músculo em destruição.",
    },
    {
      id: "carta5-nv2",
      name: "Afinidade Arcanum",
      img: "icons/svg/mystery-man.svg",
      buff1: "arcana",
      buff2: "erudition",
      hp: 1,
      description: "Magia instintiva, sem esforço aparente.",
    },
    {
      id: "carta6-nv2",
      name: "Avanço Imparável",
      img: "icons/svg/forward.svg",
      buff1: "dexterity",
      buff2: "letality",
      hp: 2,
      description: "Movimento veloz e devastador.",
    }
  ],
  3: [ /* ... */ ],
};
