export const CardsDB = {
  1: [
    {
      id: "carta1-nv1",
      name: "O Cavaleiro",
      img: "systems/tm/styles/assets/cards/1_1.webp",
      buff1: "letality",
      buff2: "virtue",
      hp: 2,
      description: "",
    },
    {
      id: "carta2-nv1",
      name: "O Plebeu",
      img: "systems/tm/styles/assets/cards/1_2.webp",
      buff1: "erudition",
      buff2: "impulse",
      hp: 1,
      description: "Resistência e estabilidade interior.",
    },
    {
      id: "carta3-nv1",
      name: "O Clérigo",
      img: "systems/tm/styles/assets/cards/1_3.webp",
      buff1: "virtue",
      buff2: "dexterity",
      hp: 3,
      description: "A centelha mágica pulsa em seu sangue.",
    },
    {
      id: "carta4-nv1",
      name: "O Mago",
      img: "systems/tm/styles/assets/cards/1_4.webp",
      buff1: "arcana",
      buff2: "erudition",
      hp: 1,
      description: "Sabedoria e espiritualidade cultivadas.",
    },
    {
      id: "carta5-nv1",
      name: "O Soldado",
      img: "systems/tm/styles/assets/cards/1_5.webp",
      buff1: "impulse",
      buff2: "erudition",
      hp: 3,
      description: "Reflexos e brutalidade predatória.",
    },
    {
      id: "carta6-nv1",
      name: "A Cigana",
      img: "systems/tm/styles/assets/cards/1_6.webp",
      buff1: "dexterity",
      buff2: "arcana",
      hp: 1,
      description: "Um corpo moldado pela sobrevivência.",
    }
  ],

   2: [
    {
      id: "carta1-nv2",
      name: "Disciplina Rígida",
      img: "icons/svg/anchor.svg",
      buff1: "virtue",
      buff2: "dexterity",
      hp: 1,
      description: "Controle mental forjado na dor.",
    },
    {
      id: "carta2-nv2",
      name: "Fôlego de Ferro",
      img: "icons/svg/breath.svg",
      buff1: "impulse",
      buff2: "arcana",
      hp: 3,
      description: "Resistência bruta alimenta o poder interno.",
    },
    {
      id: "carta3-nv2",
      name: "Estudo Obsessivo",
      img: "icons/svg/lamp.svg",
      buff1: "erudition",
      buff2: "virtue",
      hp: 0,
      description: "Nada supera a mente disciplinada.",
    },
    {
      id: "carta4-nv2",
      name: "Explosão Selvagem",
      img: "icons/svg/explosion.svg",
      buff1: "letality",
      buff2: "impulse",
      hp: 0,
      description: "Fúria que transforma músculo em destruição.",
    },
    {
      id: "carta5-nv2",
      name: "Afinidade Arcanum",
      img: "icons/svg/mystery-man.svg",
      buff1: "arcana",
      buff2: "erudition",
      hp: 1,
      description: "Magia instintiva, sem esforço aparente.",
    },
    {
      id: "carta6-nv2",
      name: "Avanço Imparável",
      img: "icons/svg/forward.svg",
      buff1: "dexterity",
      buff2: "letality",
      hp: 2,
      description: "Movimento veloz e devastador.",
    }
  ],
  3: [ /* ... */ ],
};
